"use client";
import { useState } from "react";
import { Cable, Plus, Smartphone } from "lucide-react";
import { Button } from "../../common/ui/button";
import { Input } from "../../common/ui/input";
import type { Connection, ImportPreview, Network, PublishingOverview, PublishingRun, PublishingSettings } from "./types";
import { usePublishing } from "./hooks";
import { PROVIDER_URLS } from "./data";

export function ConnectionsView({ initial }: { initial: PublishingOverview }) {
  const { data = initial, error, busy, run } = usePublishing(undefined, initial);
  const [provider, setProvider] = useState<Connection["provider"]>("iphone"), [name, setName] = useState("iPhone"), [notice, setNotice] = useState("");
  return <section className="space-y-6"><header><h2 className="flex items-center gap-2 text-xl font-medium"><Cable className="size-5" aria-hidden />Publishing</h2><p className="mt-1 text-sm text-muted-foreground">Connect your accounts, set your schedule and publish from this computer.</p></header><div role="alert" className="whitespace-pre-wrap text-sm text-destructive">{error}</div><p role="status" className="text-sm">{notice}</p>
    <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-medium"><Smartphone className="size-4" aria-hidden />iPhone Mirroring</h3><p className="text-sm text-muted-foreground">Open Mirroring with your locked iPhone nearby. macOS needs Accessibility and Screen Recording permission for the application running Agentcut. Restart that application after granting Screen Recording.</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={async () => { const result = await run({ tool: "publishing.phone.build" }); if (result) setNotice("Phone tool built. Check the connection next."); }}>Build phone tool</Button><Button variant="outline" disabled={busy} onClick={async () => { const result = await run<{ message: string }>({ tool: "publishing.phone.readiness" }); if (result) setNotice(result.message); }}>Check phone connection</Button></div></section>
    {data.connections.map(c => <ConnectionForm key={c.id} connection={c} data={data} run={run} busy={busy} />)}
    <fieldset disabled={busy} className="space-y-3 rounded-xl border p-4"><legend className="px-1 text-sm font-medium">Add connection</legend><label className="block text-sm">Publishing route<select className="mt-1 min-h-10 w-full rounded-lg border bg-background px-3" value={provider} onChange={e => { setProvider(e.target.value as Connection["provider"]); setName(e.target.options[e.target.selectedIndex].text); }}><option value="iphone">iPhone Mirroring</option><option value="postgun">Postgun</option><option value="postbridge">Postbridge</option></select></label><label className="block text-sm">Connection name<Input value={name} onChange={e => setName(e.target.value)} /></label><Button onClick={() => void run({ tool: "publishing.connection.save", provider, name, baseUrl: PROVIDER_URLS[provider] })}><Plus />Add connection</Button></fieldset>
    <ScheduleSettings key={data.settings.revision} initial={data.settings} data={data} run={run} busy={busy} />
    <ImportForm run={run} busy={busy} />
  </section>;
}

function ConnectionForm({ connection: c, data, run, busy }: { connection: Connection; data: PublishingOverview; run: PublishingRun; busy: boolean }) {
  const [key, setKey] = useState(""), [url, setUrl] = useState(c.baseUrl), [network, setNetwork] = useState<Network>("instagram"), [name, setName] = useState(""), [handle, setHandle] = useState(""), [link, setLink] = useState("");
  return <section className="space-y-3 rounded-xl border p-4"><h3 className="font-medium">{c.name}</h3><p className="text-xs text-muted-foreground">{c.configured ? "Configured" : "Needs setup"}{c.checkedAt ? ` · checked ${new Date(c.checkedAt).toLocaleString()}` : " · not checked yet"}</p>{c.error && <p className="text-sm text-destructive">{c.error}</p>}
    {c.provider !== "iphone" && <fieldset disabled={busy} className="space-y-3"><label className="block text-sm">API URL<Input value={url} onChange={e => setUrl(e.target.value)} /></label><label className="block text-sm">API key (write only)<Input type="password" autoComplete="new-password" value={key} onChange={e => setKey(e.target.value)} /></label><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={async () => { const result = await run({ tool: "publishing.connection.save", id: c.id, provider: c.provider, name: c.name, baseUrl: url, ...(key ? { key } : {}) }); if (result) setKey(""); }}>Save connection</Button><Button variant="outline" onClick={() => void run({ tool: "publishing.accounts.sync", connectionId: c.id })}>Check and refresh accounts</Button><Button variant="outline" onClick={() => void run({ tool: "publishing.calendar.sync", connectionId: c.id })}>Refresh provider calendar</Button></div></fieldset>}
    {c.provider === "postbridge" && <div className="flex flex-wrap gap-2">{(["instagram", "tiktok"] as const).map(network => <Button key={network} variant="outline" disabled={busy || !c.configured} onClick={async () => { const result = await run<{ url: string }>({ tool: "publishing.connection.link", connectionId: c.id, network, returnUrl: `${window.location.origin}/settings/publishing` }); if (result) setLink(result.url); }}>Connect {network}</Button>)}{link && <a href={link} target="_blank" rel="noreferrer" className="self-center text-sm underline">Open provider consent page</a>}<p className="text-xs text-muted-foreground">Connect YouTube in Postbridge directly. After consent, refresh accounts here.</p></div>}
    <ul className="space-y-2">{data.accounts.filter(a => a.connectionId === c.id).map(a => <li key={a.id} className="text-sm">{a.name} · {a.network}{a.needsReconnect && " · reconnect in provider"}{a.disabled && " · unavailable"}<label className="mt-1 block text-xs">Same account through another route<select className="ml-2 min-h-10 rounded-lg border bg-background px-2" value={a.equivalentTo ?? ""} disabled={busy} onChange={e => void run({ tool: "publishing.account.link", accountId: a.id, equivalentTo: e.target.value || null })}><option value="">Independent account</option>{data.accounts.filter(other => other.id !== a.id && other.network === a.network && !other.equivalentTo).map(other => <option key={other.id} value={other.id}>{other.name} · {data.connections.find(c => c.id === other.connectionId)?.name}</option>)}</select></label></li>)}</ul>
    {c.provider === "iphone" && <fieldset disabled={busy} className="space-y-3"><legend className="mb-2 text-sm font-medium">Account already signed in on the phone</legend><label className="block text-sm">Network<select className="min-h-10 w-full rounded-lg border bg-background px-3" value={network} onChange={e => setNetwork(e.target.value as Network)}><option value="instagram">Instagram</option><option value="tiktok">TikTok</option><option value="youtube">YouTube</option></select></label><label className="block text-sm">Account name<Input value={name} onChange={e => setName(e.target.value)} /></label><label className="block text-sm">Exact account handle or channel ID<Input value={handle} onChange={e => setHandle(e.target.value)} /></label><Button variant="outline" onClick={() => void run({ tool: "publishing.account.phone", connectionId: c.id, network, name, remoteId: `${network}:${handle}` })}>Add phone account</Button></fieldset>}
  </section>;
}

function ScheduleSettings({ initial, data, run, busy }: { initial: PublishingSettings; data: PublishingOverview; run: PublishingRun; busy: boolean }) {
  const [draft, setDraft] = useState(initial);
  return <fieldset disabled={busy} className="space-y-4 rounded-xl border p-4"><legend className="px-1 font-medium">Publication defaults</legend><label className="block text-sm">Timezone<Input value={draft.timezone} onChange={e => setDraft({ ...draft, timezone: e.target.value })} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Minimum spacing (minutes)<Input type="number" min="1" value={draft.minGapMinutes} onChange={e => setDraft({ ...draft, minGapMinutes: Number(e.target.value) })} /></label><label className="text-sm">Preparation time (minutes)<Input type="number" min="1" value={draft.leadMinutes} onChange={e => setDraft({ ...draft, leadMinutes: Number(e.target.value) })} /></label></div><p className="text-sm font-medium">Weekly publication times</p>
    {draft.slots.map((slot, index) => <div key={index} className="flex flex-wrap gap-2"><label className="text-sm">Day<select className="block min-h-10 rounded-lg border bg-background px-3" value={slot.weekday} onChange={e => setDraft({ ...draft, slots: draft.slots.map((s, i) => i === index ? { ...s, weekday: Number(e.target.value) } : s) })}>{["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].map((day, n) => <option value={n} key={day}>{day}</option>)}</select></label><label className="text-sm">Time<Input type="time" value={slot.time} onChange={e => setDraft({ ...draft, slots: draft.slots.map((s, i) => i === index ? { ...s, time: e.target.value } : s) })} /></label><Button variant="ghost" aria-label={`Remove weekly time ${index + 1}`} onClick={() => setDraft({ ...draft, slots: draft.slots.filter((_, i) => i !== index) })}>Remove</Button></div>)}
    <Button variant="outline" onClick={() => setDraft({ ...draft, slots: [...draft.slots, { weekday: 1, time: "18:00" }] })}>Add weekly time</Button><p className="text-sm font-medium">Default accounts</p>{data.accounts.map(a => <label key={a.id} className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={draft.defaultAccountIds.includes(a.id)} onChange={e => setDraft({ ...draft, defaultAccountIds: e.target.checked ? [...draft.defaultAccountIds, a.id] : draft.defaultAccountIds.filter(id => id !== a.id) })} />{a.name} · {a.network}</label>)}<label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={draft.autoPrepare} onChange={e => setDraft({ ...draft, autoPrepare: e.target.checked })} />Prepare text and reserve slots automatically for generated clips</label><label className="block text-sm">Writing guidance<textarea rows={3} className="mt-1 w-full rounded-lg border bg-background p-3" value={draft.writing} onChange={e => setDraft({ ...draft, writing: e.target.value })} /></label><label className="block text-sm">Screenshot retention (days)<Input type="number" min="1" max="3650" value={draft.evidenceRetentionDays} onChange={e => setDraft({ ...draft, evidenceRetentionDays: Number(e.target.value) })} /></label><Button variant="outline" onClick={() => void run({ tool: "publishing.evidence.cleanup" })}>Remove expired session screenshots</Button><details><summary className="cursor-pointer text-sm">Existing phone tool</summary><label className="mt-3 block text-sm">Executable path (optional)<Input value={draft.phoneBinary} onChange={e => setDraft({ ...draft, phoneBinary: e.target.value })} /></label></details><Button onClick={() => void run({ tool: "publishing.settings.save", settings: draft })}>Save publication defaults</Button></fieldset>;
}

function ImportForm({ run, busy }: { run: PublishingRun; busy: boolean }) {
  const [file, setFile] = useState(""), [map, setMap] = useState("{}"), [sourceMap, setSourceMap] = useState("{}"), [importId, setImportId] = useState(""), [preview, setPreview] = useState<ImportPreview | null>(null), [error, setError] = useState("");
  return <details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">Import existing Cadence publications</summary><div className="mt-4 space-y-3"><p className="text-sm text-muted-foreground">One-time import from a Cadence database or exported posts JSON. It does not send anything. Stop Cadence dispatch for imported work at cutover.</p><label className="block text-sm">Local database or JSON file<Input value={file} onChange={e => { setFile(e.target.value); setPreview(null); }} /></label><label className="block text-sm">Account mapping (Cadence ID → Agentcut ID, JSON)<textarea className="w-full rounded-lg border bg-background p-3 font-mono text-xs" value={map} onChange={e => { setMap(e.target.value); setPreview(null); }} /></label><label className="block text-sm">Video mapping (Cadence post ID → projectId and sequenceId, JSON)<textarea className="w-full rounded-lg border bg-background p-3 font-mono text-xs" value={sourceMap} onChange={e => { setSourceMap(e.target.value); setPreview(null); }} /></label><Button variant="outline" disabled={busy} onClick={async () => { try { const result = await run<ImportPreview>({ tool: "publication.import.preview", file, accountMap: JSON.parse(map), sourceMap: JSON.parse(sourceMap) }); if (result) setPreview(result); } catch { setError("Enter a valid JSON account mapping."); } }}>Preview import</Button>{preview && <><p className="text-sm">{preview.entries.length} ready · {preview.existing} already imported</p><ul className="space-y-1 text-xs text-muted-foreground">{preview.issues.map((issue, i) => <li key={i}>{issue.message}</li>)}</ul><Button disabled={busy} onClick={async () => { try { const accountMap = JSON.parse(map); const result = await run<{ importId: string }>({ tool: "publication.import.apply", file, accountMap, sourceMap: JSON.parse(sourceMap) }); if (result) { setPreview(null); setImportId(result.importId); } } catch { setError("Enter a valid JSON account mapping."); } }}>Import local records</Button></>}{importId && <Button variant="outline" disabled={busy} onClick={async () => { const result = await run({ tool: "publication.import.rollback", importId }); if (result) setImportId(""); }}>Undo untouched local import</Button>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</div></details>;
}
