import { useId, type ReactNode, type SVGProps } from "react";

/**
 * The agentcut mark. Generated by `node scripts/brand-assets.mjs` — change the
 * geometry there, not here, or the next run will overwrite you.
 *
 * The rings, the blades and the eyes all overlap, so neither fill rule punches the
 * holes cleanly; a mask does, and `currentColor` survives because what the mask
 * reveals is a rect painted with it. The id comes from `useId` so two marks on one
 * page can't collide — with the colons stripped, since `url(#:r0:)` is not a
 * selector any browser will resolve.
 *
 * Reach for `AgentcutMark` in the UI: its blades are thickened for the sizes the
 * interface actually renders at. `AgentcutMarkLarge` is the full drawing — sharper
 * tips, a slight tilt, a glint in each eye — and wants 48px or more.
 */
type MarkProps = SVGProps<SVGSVGElement>;

const mark = (body: (id: string) => ReactNode) =>
  function Mark({ className = "size-6", ...props }: MarkProps) {
    const id = `m${useId().replace(/:/g, "")}`;
    return (
      <svg viewBox="0 0 100 100" fill="none" aria-hidden focusable="false" className={className} {...props}>
        {body(id)}
      </svg>
    );
  };

export const AgentcutMark = mark((id) => (
  <>
    <mask id={id} maskUnits="userSpaceOnUse" x="0" y="0" width="100" height="100">
      <g fill="#fff"><g transform="translate(50 51) scale(0.94) translate(-50 -50)"><g transform="rotate(0 50 50)"><circle cx="32.5" cy="70" r="22"/><circle cx="67.5" cy="70" r="22"/><path d="M17 13C33.82 20.08 48.32 30.41 60.5 44L36 55C29.67 41 23.33 27 17 13Z"/><g transform="translate(100 0) scale(-1 1)"><path d="M17 13C33.82 20.08 48.32 30.41 60.5 44L36 55C29.67 41 23.33 27 17 13Z"/></g></g></g></g>
      <g fill="#000"><g transform="translate(50 51) scale(0.94) translate(-50 -50)"><g transform="rotate(0 50 50)"><ellipse cx="32.5" cy="68.8" rx="8.6" ry="10.4"/><ellipse cx="67.5" cy="68.8" rx="8.6" ry="10.4"/><circle cx="50" cy="49.5" r="4"/></g></g></g>
    </mask>
    <rect width="100" height="100" fill="currentColor" mask={`url(#${id})`} />
  </>
));

export const AgentcutMarkLarge = mark((id) => (
  <>
    <mask id={id} maskUnits="userSpaceOnUse" x="0" y="0" width="100" height="100">
      <g fill="#fff"><g transform="translate(50 51) scale(0.86) translate(-50 -50)"><g transform="rotate(-4 50 50)"><circle cx="32" cy="72" r="21"/><circle cx="68" cy="72" r="21"/><path d="M13 9C30.97 17.02 46.14 28.69 58.5 44L38 55C29.67 39.67 21.33 24.33 13 9Z"/><g transform="translate(100 0) scale(-1 1)"><path d="M13 9C30.97 17.02 46.14 28.69 58.5 44L38 55C29.67 39.67 21.33 24.33 13 9Z"/></g></g></g></g>
      <g fill="#000"><g transform="translate(50 51) scale(0.86) translate(-50 -50)"><g transform="rotate(-4 50 50)"><ellipse cx="32" cy="69.4" rx="9.4" ry="12.4"/><ellipse cx="68" cy="69.4" rx="9.4" ry="12.4"/><circle cx="50" cy="49.5" r="3.6"/></g></g></g>
      <g fill="#fff"><g transform="translate(50 51) scale(0.86) translate(-50 -50)"><g transform="rotate(-4 50 50)"><circle cx="35.38" cy="63.7" r="2.35"/><circle cx="71.38" cy="63.7" r="2.35"/></g></g></g>
    </mask>
    <rect width="100" height="100" fill="currentColor" mask={`url(#${id})`} />
  </>
));
